"""
LLM interface for FinSight AI.

The financial intelligence engine remains deterministic and
grounded in structured financial analytics.

This module provides the interface through which a real LLM
can be connected later without changing the core analytics.
"""


def generate_ai_response(prompt, context=None):
    """
    Generate an AI interpretation from a grounded financial prompt.

    Current mode:
        DEMO / MOCK

    Future mode:
        A real LLM provider can be connected here using the same
        function interface.

    Parameters
    ----------
    prompt : str
        Grounded prompt generated by the AI investigation layer.

    context : dict, optional
        Structured financial context used to ground the response.

    Returns
    -------
    dict
        Standardized AI response.
    """

    context = context or {}

    if not prompt:
        return {
            "status": "ERROR",
            "response": "No AI prompt was provided.",
            "context_available": bool(context)
        }

    return {
        "status": "DEMO",
        "provider": "Local FinSight AI",
        "response": (
            "FinSight AI is currently running in demo mode. "
            "The financial intelligence engine has prepared "
            "grounded financial evidence, risk signals, "
            "anomalies, and peer benchmarks for AI interpretation."
        ),
        "context_available": bool(context),
        "prompt_ready": True
    }


def get_llm_status():
    """
    Return the current LLM integration status.
    """

    return {
        "mode": "DEMO",
        "provider": "Local FinSight AI",
        "api_connected": False,
        "ready_for_provider_integration": True
    }
